/*
    formgen.js

    Generates the server-side collector script for forms that save to a file.

    A published form can either post to a URL the site owner supplies, or - the
    default, and the point of this module - to a small .agi script the builder
    writes into the site at publish time. That script appends each submission as
    a row to a CSV file in the owner's own storage, which they can then open in
    the ArozOS Office suite.

    The generated script hardcodes its target path and field list. That is
    deliberate: it is regenerated on every publish, so it always matches the
    form it belongs to, and it needs no configuration of its own.

    Why the collector is a .agi file: the personal-site router executes .agi
    files instead of serving them (see mod/www/www.go), running them as the site
    owner - which is exactly the permission needed to write to the owner's
    files, and never exposes the script's source to visitors.
*/

var WBFormGen = (function () {

    var DEFAULT_DIR = "user:/Form Submissions";

    /* Where a form saves to when the user has not chosen a path. */
    function defaultPath(node) {
        var base = String(node.props.formName || "form")
            .replace(/[^A-Za-z0-9 _-]+/g, "").trim().replace(/\s+/g, "-").toLowerCase();
        if (!base) { base = "form"; }
        return DEFAULT_DIR + "/" + base + ".csv";
    }

    function targetPath(node) {
        return String(node.props.csvPath || "").trim() || defaultPath(node);
    }

    /* Every file-backed form in the project, with the page it lives on. */
    function collect(project) {
        var out = [];
        project.pages.forEach(function (page) {
            if (page.visibility === "hidden") { return; }
            (function walk(node) {
                if (WBRender.formUsesFile(node)) { out.push({ node: node, page: page }); }
                for (var i = 0; i < node.children.length; i++) { walk(node.children[i]); }
            })(page.root);
        });
        return out;
    }

    /* Quote a JS string literal for embedding in the generated source. */
    function lit(value) {
        return JSON.stringify(String(value === undefined || value === null ? "" : value));
    }

    function litArray(values) {
        return "[" + values.map(lit).join(", ") + "]";
    }

    /*
        Build the collector script for one form.
        project/page are used for the look and the "back" link of the reply page.
    */
    function script(project, node, page) {
        var fields = WBRender.collectFormFields(node);
        var names = fields.map(function (f) { return WBRender.formFieldName(f); });
        var labels = fields.map(function (f) { return WBRender.formFieldLabel(f); });
        var theme = (project.settings && project.settings.theme) || {};
        var backFile = page ? WBModel.pageFileName(page) : "index.html";

        var headers = ["Submitted at"].concat(labels);

        return [
            "/*",
            "    " + (node.props.formName || "Form") + " - submission collector",
            "",
            "    Generated by the ArozOS Site Builder. This file is rewritten every time",
            "    the site is published, so any edits made here will be lost.",
            "",
            "    Submissions are appended to:",
            "        " + targetPath(node),
            "",
            "    Note: rows are appended with a read-modify-write, so two submissions",
            "    landing in the same instant could overwrite one another. That is fine",
            "    for a personal site; a busy form wants a real database instead.",
            "*/",
            "",
            "requirelib(\"filelib\");",
            "",
            "/*",
            "    The AGI runtime starts every script with HTTP_HEADER set to \"text/plain\",",
            "    and the personal-site router applies that to the response - so without this",
            "    line the browser would show the reply page as raw markup.",
            "*/",
            "HTTP_HEADER = \"text/html; charset=utf-8\";",
            "",
            "var TARGET  = " + lit(targetPath(node)) + ";",
            "var HEADERS = " + litArray(headers) + ";",
            "var FIELDS  = " + litArray(names) + ";",
            "var TITLE   = " + lit(node.props.successTitle || "Thank you") + ";",
            "var SUCCESS = " + lit(node.props.successMessage ||
                "Thank you. Your message has been received.") + ";",
            "var BACKTEXT= " + lit(node.props.backLabel || "Back to the site") + ";",
            "var SITE    = " + lit(project.name || "") + ";",
            "var BACK    = " + lit("../" + backFile) + ";",
            "/* blank in the inspector means \"follow the site theme\" */",
            "var ACCENT  = " + lit(node.props.replyAccent || theme.accent || "#f97316") + ";",
            "var BG      = " + lit(node.props.replyBg || theme.background || "#ffffff") + ";",
            "var TEXT    = " + lit(node.props.replyText || theme.text || "#16181d") + ";",
            "",
            "/* RFC 4180 quoting: wrap in quotes when needed, double the quotes inside. */",
            "function csvCell(value) {",
            "    var v = (value === null || value === undefined) ? \"\" : String(value);",
            "    v = v.split(\"\\r\\n\").join(\" \").split(\"\\n\").join(\" \").split(\"\\r\").join(\" \");",
            "    if (v.indexOf(\"\\\"\") >= 0 || v.indexOf(\",\") >= 0 || v.indexOf(\";\") >= 0) {",
            "        v = \"\\\"\" + v.split(\"\\\"\").join(\"\\\"\\\"\") + \"\\\"\";",
            "    }",
            "    return v;",
            "}",
            "",
            "function pad(n) { return (n < 10 ? \"0\" : \"\") + n; }",
            "",
            "function timestamp() {",
            "    var d = new Date();",
            "    return d.getFullYear() + \"-\" + pad(d.getMonth() + 1) + \"-\" + pad(d.getDate()) +",
            "           \" \" + pad(d.getHours()) + \":\" + pad(d.getMinutes()) + \":\" + pad(d.getSeconds());",
            "}",
            "",
            "function parentDir(p) {",
            "    var i = p.lastIndexOf(\"/\");",
            "    if (i <= 0) { return \"\"; }",
            "    return p.substring(0, i);",
            "}",
            "",
            "function esc(s) {",
            "    return String(s === null || s === undefined ? \"\" : s)",
            "        .split(\"&\").join(\"&amp;\").split(\"<\").join(\"&lt;\").split(\">\").join(\"&gt;\");",
            "}",
            "",
            "/* The page a visitor sees after posting the form. */",
            "function replyPage(title, message) {",
            "    return \"<!DOCTYPE html><html lang=\\\"en\\\"><head><meta charset=\\\"utf-8\\\">\" +",
            "        \"<meta name=\\\"viewport\\\" content=\\\"width=device-width, initial-scale=1\\\">\" +",
            "        \"<title>\" + esc(title) + (SITE ? \" - \" + esc(SITE) : \"\") + \"</title><style>\" +",
            "        \"body{margin:0;min-height:100vh;display:flex;align-items:center;justify-content:center;\" +",
            "        \"background:\" + BG + \";color:\" + TEXT + \";\" +",
            "        \"font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;padding:24px}\" +",
            "        \".card{max-width:460px;text-align:center}\" +",
            "        \".mark{width:56px;height:56px;border-radius:50%;background:\" + ACCENT + \";\" +",
            "        \"display:flex;align-items:center;justify-content:center;margin:0 auto 22px}\" +",
            "        \"h1{font-size:26px;margin:0 0 12px;letter-spacing:-0.02em}\" +",
            "        \"p{font-size:16px;line-height:1.6;opacity:.72;margin:0 0 26px}\" +",
            "        \"a{display:inline-block;padding:12px 26px;border-radius:8px;background:\" + ACCENT + \";\" +",
            "        \"color:#fff;text-decoration:none;font-weight:600;font-size:15px}\" +",
            "        \"</style></head><body><div class=\\\"card\\\">\" +",
            "        \"<div class=\\\"mark\\\"><svg width=\\\"26\\\" height=\\\"26\\\" viewBox=\\\"0 0 24 24\\\" fill=\\\"none\\\" \" +",
            "        \"stroke=\\\"#fff\\\" stroke-width=\\\"2\\\" stroke-linecap=\\\"round\\\" stroke-linejoin=\\\"round\\\">\" +",
            "        \"<path d=\\\"M4.5 12.5l5 5 10-11\\\"/></svg></div>\" +",
            "        \"<h1>\" + esc(title) + \"</h1><p>\" + esc(message) + \"</p>\" +",
            "        \"<a href=\\\"\" + BACK + \"\\\">\" + esc(BACKTEXT) + \"</a></div></body></html>\";",
            "}",
            "",
            "function appendRow(cells) {",
            "    var dir = parentDir(TARGET);",
            "    if (dir !== \"\" && !filelib.fileExists(dir)) {",
            "        filelib.mkdir(dir);",
            "    }",
            "    var line = cells.join(\",\");",
            "",
            "    if (!filelib.fileExists(TARGET)) {",
            "        /* a BOM so spreadsheet apps read the file as UTF-8 */",
            "        return filelib.writeFile(TARGET, \"\\uFEFF\" + HEADERS.join(\",\") + \"\\n\" + line + \"\\n\");",
            "    }",
            "",
            "    var existing = filelib.readFile(TARGET);",
            "    if (existing === null || existing === undefined) { existing = \"\"; }",
            "    if (existing.length > 0 && existing.charAt(existing.length - 1) !== \"\\n\") {",
            "        existing = existing + \"\\n\";",
            "    }",
            "    return filelib.writeFile(TARGET, existing + line + \"\\n\");",
            "}",
            "",
            "function main() {",
            "    if (REQ_METHOD !== \"POST\") {",
            "        sendResp(replyPage(\"Nothing to see here\",",
            "            \"This address only accepts form submissions.\"));",
            "        return;",
            "    }",
            "",
            "    /* Hidden bait field: real visitors never see it, most bots fill it in. */",
            "    var trap = postPara(\"_hp\");",
            "    if (trap !== null && String(trap) !== \"\") {",
            "        sendResp(replyPage(TITLE, SUCCESS));",
            "        return;",
            "    }",
            "",
            "    var cells = [csvCell(timestamp())];",
            "    for (var i = 0; i < FIELDS.length; i++) {",
            "        var value = postPara(FIELDS[i]);",
            "        cells.push(csvCell(value === null ? \"\" : value));",
            "    }",
            "",
            "    if (appendRow(cells) === false) {",
            "        sendResp(replyPage(\"Could not save your message\",",
            "            \"Something went wrong while saving. Please try again later.\"));",
            "        return;",
            "    }",
            "",
            "    sendResp(replyPage(TITLE, SUCCESS));",
            "}",
            "",
            "main();",
            ""
        ].join("\n");
    }

    /* The files to add to a published site for its file-backed forms. */
    function files(project) {
        return collect(project).map(function (entry) {
            return {
                path: WBRender.formEndpoint(entry.node),
                content: script(project, entry.node, entry.page)
            };
        });
    }

    return {
        DEFAULT_DIR: DEFAULT_DIR,
        defaultPath: defaultPath,
        targetPath: targetPath,
        collect: collect,
        script: script,
        files: files
    };
})();
