/*
    ArozOS Office Sheets - function help text
    =========================================
    One line of description and one worked example per formula function,
    shown by the function suggestion popup (sheets_suggest.js). The usage
    line comes from the engine itself (spec.syntax in formula_fn_*.js), so
    only prose and examples live here.

        SheetFormulaHelp[NAME] = [description, example]

    test_formula.js fails when a registered function has no entry here, so
    add one whenever you defineFunction a new name.
*/
var SheetFormulaHelp = {
    "ABS": ["Absolute value of a number.", "ABS(-7)"],
    "ACOS": ["Inverse cosine of a value, in radians.", "ACOS(0.5)"],
    "ACOSH": ["Inverse hyperbolic cosine of a number.", "ACOSH(2)"],
    "ACOT": ["Inverse cotangent of a value, in radians.", "ACOT(1)"],
    "ACOTH": ["Inverse hyperbolic cotangent of a value (|value| > 1).", "ACOTH(3)"],
    "ADD": ["Sum of two numbers. Same as the + operator.", "ADD(A1, 5)"],
    "ADDRESS": ["Cell reference as text, built from a row and column number.", "ADDRESS(2, 3)"],
    "AND": ["TRUE when every argument is TRUE.", "AND(A1 > 0, B1 > 0)"],
    "ARABIC": ["Converts a Roman numeral to a number.", "ARABIC(\"XIV\")"],
    "ARRAYFORMULA": ["Evaluates an expression over whole ranges and spills the result.", "ARRAYFORMULA(A1:A10 * B1:B10)"],
    "ARRAY_CONSTRAIN": ["Trims an array result to a given number of rows and columns.", "ARRAY_CONSTRAIN(A1:D10, 3, 2)"],
    "ASC": ["Converts full-width characters to half-width.", "ASC(A1)"],
    "ASIN": ["Inverse sine of a value, in radians.", "ASIN(0.5)"],
    "ASINH": ["Inverse hyperbolic sine of a number.", "ASINH(1)"],
    "ATAN": ["Inverse tangent of a value, in radians.", "ATAN(1)"],
    "ATAN2": ["Angle between the x-axis and the point (x, y), in radians.", "ATAN2(1, 1)"],
    "ATANH": ["Inverse hyperbolic tangent of a number.", "ATANH(0.5)"],
    "AVEDEV": ["Average magnitude of deviations from the mean.", "AVEDEV(A1:A10)"],
    "AVERAGE": ["Arithmetic mean of the numbers, ignoring text.", "AVERAGE(A1:A10)"],
    "AVERAGE.WEIGHTED": ["Weighted average of values, given matching weights.", "AVERAGE.WEIGHTED(A1:A5, B1:B5)"],
    "AVERAGEA": ["Mean of the values, counting text as 0 and TRUE as 1.", "AVERAGEA(A1:A10)"],
    "AVERAGEIF": ["Average of the cells that meet one criterion.", "AVERAGEIF(A1:A10, \">50\")"],
    "AVERAGEIFS": ["Average of a range, counting only rows that meet every criterion.", "AVERAGEIFS(C1:C10, A1:A10, \"East\", B1:B10, \">100\")"],
    "BASE": ["Converts a number to text in another base (2-36).", "BASE(255, 16)"],
    "BIN2DEC": ["Converts a binary number to decimal.", "BIN2DEC(\"1101\")"],
    "BIN2HEX": ["Converts a binary number to hexadecimal.", "BIN2HEX(\"11111111\")"],
    "BIN2OCT": ["Converts a binary number to octal.", "BIN2OCT(\"1001\")"],
    "BITAND": ["Bitwise AND of two numbers.", "BITAND(12, 10)"],
    "BITLSHIFT": ["Shifts the bits of a number left.", "BITLSHIFT(4, 2)"],
    "BITOR": ["Bitwise OR of two numbers.", "BITOR(12, 10)"],
    "BITRSHIFT": ["Shifts the bits of a number right.", "BITRSHIFT(16, 2)"],
    "BITXOR": ["Bitwise exclusive OR of two numbers.", "BITXOR(12, 10)"],
    "CEILING": ["Rounds a number up to the nearest multiple of factor.", "CEILING(4.2, 0.5)"],
    "CEILING.MATH": ["Rounds up to a multiple of significance, with a mode for negatives.", "CEILING.MATH(-4.2, 1, 1)"],
    "CEILING.PRECISE": ["Rounds up to a multiple of significance, regardless of sign.", "CEILING.PRECISE(4.2, 2)"],
    "CELL": ["Information about a cell, such as its address, row or contents.", "CELL(\"address\", B3)"],
    "CHAR": ["Character for a character-code number.", "CHAR(65)"],
    "CHOOSE": ["Picks one of the choices by its position.", "CHOOSE(2, \"Low\", \"Mid\", \"High\")"],
    "CHOOSECOLS": ["Columns picked from an array by their numbers.", "CHOOSECOLS(A1:D10, 1, 3)"],
    "CHOOSEROWS": ["Rows picked from an array by their numbers.", "CHOOSEROWS(A1:D10, 1, -1)"],
    "CLEAN": ["Removes non-printable characters from text.", "CLEAN(A1)"],
    "CODE": ["Character code of the first character of text.", "CODE(\"A\")"],
    "COLUMN": ["Column number of a cell (of this cell when omitted).", "COLUMN(C5)"],
    "COLUMNS": ["Number of columns in a range.", "COLUMNS(A1:D10)"],
    "COMBIN": ["Number of ways to choose k items from n, order ignored.", "COMBIN(10, 3)"],
    "COMBINA": ["Combinations of k items from n, repetition allowed.", "COMBINA(4, 3)"],
    "CONCAT": ["Joins values together into one piece of text.", "CONCAT(A1, \" \", B1)"],
    "CONCATENATE": ["Joins values together into one piece of text.", "CONCATENATE(A1, \" \", B1)"],
    "CONVERT": ["Converts a value from one unit of measure to another.", "CONVERT(10, \"km\", \"mi\")"],
    "CORREL": ["Pearson correlation coefficient of two data sets.", "CORREL(B1:B10, A1:A10)"],
    "COS": ["Cosine of an angle given in radians.", "COS(PI())"],
    "COSH": ["Hyperbolic cosine of a number.", "COSH(1)"],
    "COT": ["Cotangent of an angle given in radians.", "COT(PI() / 4)"],
    "COTH": ["Hyperbolic cotangent of a number.", "COTH(1)"],
    "COUNT": ["Number of numeric values.", "COUNT(A1:A10)"],
    "COUNTA": ["Number of non-empty values.", "COUNTA(A1:A10)"],
    "COUNTBLANK": ["Number of empty cells in a range.", "COUNTBLANK(A1:A10)"],
    "COUNTIF": ["Number of cells that meet a criterion.", "COUNTIF(A1:A10, \">50\")"],
    "COUNTIFS": ["Number of rows that meet every criterion.", "COUNTIFS(A1:A10, \"East\", B1:B10, \">100\")"],
    "COUNTUNIQUE": ["Number of distinct values.", "COUNTUNIQUE(A1:A10)"],
    "COVAR": ["Population covariance of two data sets.", "COVAR(B1:B10, A1:A10)"],
    "COVARIANCE.P": ["Population covariance of two data sets.", "COVARIANCE.P(B1:B10, A1:A10)"],
    "COVARIANCE.S": ["Sample covariance of two data sets.", "COVARIANCE.S(B1:B10, A1:A10)"],
    "CSC": ["Cosecant of an angle given in radians.", "CSC(PI() / 2)"],
    "CSCH": ["Hyperbolic cosecant of a number.", "CSCH(1)"],
    "CUMIPMT": ["Cumulative interest paid on a loan between two periods.", "CUMIPMT(0.05 / 12, 360, 200000, 1, 12, 0)"],
    "CUMPRINC": ["Cumulative principal paid on a loan between two periods.", "CUMPRINC(0.05 / 12, 360, 200000, 1, 12, 0)"],
    "DATE": ["Date built from a year, month and day.", "DATE(2026, 9, 22)"],
    "DATEDIF": ["Difference between two dates in days (\"D\"), months (\"M\") or years (\"Y\").", "DATEDIF(A1, B1, \"M\")"],
    "DATEVALUE": ["Converts text that looks like a date into a date.", "DATEVALUE(\"2026-09-22\")"],
    "DAVERAGE": ["Average of a database column, over the records that meet the criteria.", "DAVERAGE(A1:D20, \"Sales\", F1:F2)"],
    "DAY": ["Day of the month of a date.", "DAY(A1)"],
    "DAYS": ["Number of days between two dates.", "DAYS(B1, A1)"],
    "DAYS360": ["Days between two dates on a 360-day year.", "DAYS360(A1, B1)"],
    "DB": ["Depreciation by the fixed-declining-balance method.", "DB(10000, 1000, 5, 1)"],
    "DCOUNT": ["Count of numbers in a database column, over matching records.", "DCOUNT(A1:D20, \"Sales\", F1:F2)"],
    "DCOUNTA": ["Count of non-empty values in a database column, over matching records.", "DCOUNTA(A1:D20, \"Name\", F1:F2)"],
    "DDB": ["Depreciation by the double-declining-balance method.", "DDB(10000, 1000, 5, 1)"],
    "DEC2BIN": ["Converts a decimal number to binary.", "DEC2BIN(13)"],
    "DEC2HEX": ["Converts a decimal number to hexadecimal.", "DEC2HEX(255)"],
    "DEC2OCT": ["Converts a decimal number to octal.", "DEC2OCT(64)"],
    "DECIMAL": ["Converts text in another base to a decimal number.", "DECIMAL(\"FF\", 16)"],
    "DEGREES": ["Converts radians to degrees.", "DEGREES(PI())"],
    "DELTA": ["1 when two numbers are equal, otherwise 0.", "DELTA(A1, B1)"],
    "DEVSQ": ["Sum of squared deviations from the mean.", "DEVSQ(A1:A10)"],
    "DGET": ["The single value of a database column that matches the criteria.", "DGET(A1:D20, \"Price\", F1:F2)"],
    "DIVIDE": ["One number divided by another. Same as the / operator.", "DIVIDE(A1, B1)"],
    "DMAX": ["Largest value of a database column, over matching records.", "DMAX(A1:D20, \"Sales\", F1:F2)"],
    "DMIN": ["Smallest value of a database column, over matching records.", "DMIN(A1:D20, \"Sales\", F1:F2)"],
    "DOLLAR": ["Formats a number as currency text.", "DOLLAR(1234.567, 2)"],
    "DOLLARDE": ["Converts a fractional price to a decimal price.", "DOLLARDE(1.02, 16)"],
    "DOLLARFR": ["Converts a decimal price to a fractional price.", "DOLLARFR(1.125, 16)"],
    "DPRODUCT": ["Product of a database column, over matching records.", "DPRODUCT(A1:D20, \"Qty\", F1:F2)"],
    "DROP": ["An array with rows (and columns) removed from the start or end.", "DROP(A1:D10, 1)"],
    "DSTDEV": ["Sample standard deviation of a database column, over matching records.", "DSTDEV(A1:D20, \"Sales\", F1:F2)"],
    "DSTDEVP": ["Population standard deviation of a database column, over matching records.", "DSTDEVP(A1:D20, \"Sales\", F1:F2)"],
    "DSUM": ["Sum of a database column, over the records that meet the criteria.", "DSUM(A1:D20, \"Sales\", F1:F2)"],
    "DVAR": ["Sample variance of a database column, over matching records.", "DVAR(A1:D20, \"Sales\", F1:F2)"],
    "DVARP": ["Population variance of a database column, over matching records.", "DVARP(A1:D20, \"Sales\", F1:F2)"],
    "EDATE": ["Date a number of months before or after a date.", "EDATE(A1, 3)"],
    "EFFECT": ["Effective annual interest rate from a nominal rate.", "EFFECT(0.05, 12)"],
    "ENCODEURL": ["Encodes text for use in a URL.", "ENCODEURL(\"a b&c\")"],
    "EOMONTH": ["Last day of the month, a number of months from a date.", "EOMONTH(A1, 0)"],
    "EPOCHTODATE": ["Converts a Unix timestamp to a date (unit 1 = seconds, 2 = ms, 3 = us).", "EPOCHTODATE(1700000000)"],
    "EQ": ["TRUE when two values are equal. Same as the = operator.", "EQ(A1, B1)"],
    "ERROR.TYPE": ["Number identifying the type of an error value.", "ERROR.TYPE(A1)"],
    "EVEN": ["Rounds a number up to the nearest even integer.", "EVEN(3.2)"],
    "EXACT": ["TRUE when two strings are identical, case included.", "EXACT(A1, B1)"],
    "EXP": ["e raised to a power.", "EXP(1)"],
    "EXPAND": ["An array grown to the given size, padding new cells.", "EXPAND(A1:B2, 3, 3, \"\")"],
    "FACT": ["Factorial of a number.", "FACT(5)"],
    "FACTDOUBLE": ["Double factorial of a number.", "FACTDOUBLE(7)"],
    "FALSE": ["The logical value FALSE.", "FALSE()"],
    "FILTER": ["The rows (or columns) of a range that meet the conditions.", "FILTER(A1:C10, B1:B10 > 100)"],
    "FIND": ["Position of text inside other text, case-sensitive.", "FIND(\"@\", A1)"],
    "FINDB": ["Byte position of text inside other text, case-sensitive.", "FINDB(\"b\", \"abc\")"],
    "FISHER": ["Fisher transformation of a value.", "FISHER(0.75)"],
    "FISHERINV": ["Inverse Fisher transformation of a value.", "FISHERINV(0.97)"],
    "FIXED": ["Formats a number with a fixed number of decimals, as text.", "FIXED(1234.567, 1)"],
    "FLATTEN": ["All values of one or more ranges in a single column.", "FLATTEN(A1:C3)"],
    "FLOOR": ["Rounds a number down to the nearest multiple of factor.", "FLOOR(4.7, 0.5)"],
    "FLOOR.MATH": ["Rounds down to a multiple of significance, with a mode for negatives.", "FLOOR.MATH(-4.7, 1, 1)"],
    "FLOOR.PRECISE": ["Rounds down to a multiple of significance, regardless of sign.", "FLOOR.PRECISE(4.7, 2)"],
    "FORECAST": ["Predicts y for a given x by linear regression.", "FORECAST(30, B1:B10, A1:A10)"],
    "FORECAST.LINEAR": ["Predicts y for a given x by linear regression.", "FORECAST.LINEAR(30, B1:B10, A1:A10)"],
    "FORMULATEXT": ["The formula of a cell, as text.", "FORMULATEXT(B2)"],
    "FREQUENCY": ["How many values fall into each class interval.", "FREQUENCY(A1:A20, C1:C4)"],
    "FV": ["Future value of an investment with periodic payments.", "FV(0.05 / 12, 120, -100)"],
    "FVSCHEDULE": ["Future value of a principal after a series of interest rates.", "FVSCHEDULE(1000, {0.05, 0.06, 0.04})"],
    "GCD": ["Greatest common divisor of the numbers.", "GCD(24, 36)"],
    "GEOMEAN": ["Geometric mean of the numbers.", "GEOMEAN(A1:A10)"],
    "GESTEP": ["1 when a value is greater than or equal to step, otherwise 0.", "GESTEP(A1, 50)"],
    "GROWTH": ["Values predicted along an exponential growth trend.", "GROWTH(B1:B10, A1:A10, A11:A12)"],
    "GT": ["TRUE when the first value is greater. Same as the > operator.", "GT(A1, B1)"],
    "GTE": ["TRUE when the first value is greater or equal. Same as >=.", "GTE(A1, B1)"],
    "HARMEAN": ["Harmonic mean of the numbers.", "HARMEAN(A1:A10)"],
    "HEX2BIN": ["Converts a hexadecimal number to binary.", "HEX2BIN(\"F\")"],
    "HEX2DEC": ["Converts a hexadecimal number to decimal.", "HEX2DEC(\"FF\")"],
    "HEX2OCT": ["Converts a hexadecimal number to octal.", "HEX2OCT(\"FF\")"],
    "HLOOKUP": ["Finds a key in the first row of a range and returns a value from another row.", "HLOOKUP(\"Qty\", A1:F3, 2, FALSE)"],
    "HOUR": ["Hour component of a time, 0-23.", "HOUR(A1)"],
    "HSTACK": ["Arrays placed side by side into one array.", "HSTACK(A1:A5, C1:C5)"],
    "HYPERLINK": ["A clickable link to a URL.", "HYPERLINK(\"https://example.com\", \"Example\")"],
    "IF": ["One value when a condition is TRUE, another when it is FALSE.", "IF(A1 > 50, \"Pass\", \"Fail\")"],
    "IFERROR": ["The value, or a fallback when the value is an error.", "IFERROR(A1 / B1, 0)"],
    "IFNA": ["The value, or a fallback when the value is #N/A.", "IFNA(VLOOKUP(A1, D1:E10, 2, FALSE), \"Not found\")"],
    "IFS": ["The value for the first condition that is TRUE.", "IFS(A1 >= 90, \"A\", A1 >= 80, \"B\", TRUE, \"C\")"],
    "INDEX": ["The cell at a given row and column of a range.", "INDEX(A1:C10, 3, 2)"],
    "INDIRECT": ["The reference named by a piece of text.", "INDIRECT(\"B\" & A1)"],
    "INT": ["Rounds a number down to the nearest integer.", "INT(8.9)"],
    "INTERCEPT": ["Y-intercept of the linear regression line.", "INTERCEPT(B1:B10, A1:A10)"],
    "IPMT": ["Interest part of a loan payment for a given period.", "IPMT(0.05 / 12, 1, 360, 200000)"],
    "IRR": ["Internal rate of return of a series of cash flows.", "IRR(A1:A6)"],
    "ISBETWEEN": ["TRUE when a value lies between two others.", "ISBETWEEN(A1, 1, 10, TRUE, TRUE)"],
    "ISBLANK": ["TRUE when a cell is empty.", "ISBLANK(A1)"],
    "ISDATE": ["TRUE when a value is a date.", "ISDATE(A1)"],
    "ISEMAIL": ["TRUE when a value looks like an email address.", "ISEMAIL(A1)"],
    "ISERR": ["TRUE for any error except #N/A.", "ISERR(A1)"],
    "ISERROR": ["TRUE for any error value.", "ISERROR(A1 / B1)"],
    "ISEVEN": ["TRUE when a number is even.", "ISEVEN(A1)"],
    "ISFORMULA": ["TRUE when a cell holds a formula.", "ISFORMULA(B2)"],
    "ISLOGICAL": ["TRUE when a value is TRUE or FALSE.", "ISLOGICAL(A1)"],
    "ISNA": ["TRUE when a value is the #N/A error.", "ISNA(A1)"],
    "ISNONTEXT": ["TRUE when a value is not text.", "ISNONTEXT(A1)"],
    "ISNUMBER": ["TRUE when a value is a number.", "ISNUMBER(A1)"],
    "ISO.CEILING": ["Rounds up to a multiple of significance, regardless of sign.", "ISO.CEILING(4.2, 2)"],
    "ISODD": ["TRUE when a number is odd.", "ISODD(A1)"],
    "ISOWEEKNUM": ["ISO week number of a date.", "ISOWEEKNUM(A1)"],
    "ISPMT": ["Interest paid in a given period of a straight-line loan.", "ISPMT(0.05 / 12, 1, 36, 8000)"],
    "ISREF": ["TRUE when a value is a cell reference.", "ISREF(A1)"],
    "ISTEXT": ["TRUE when a value is text.", "ISTEXT(A1)"],
    "ISURL": ["TRUE when a value looks like a URL.", "ISURL(A1)"],
    "JOIN": ["Joins values with a delimiter between them.", "JOIN(\", \", A1:A5)"],
    "KURT": ["Kurtosis of a data set.", "KURT(A1:A10)"],
    "LARGE": ["The n-th largest value of a data set.", "LARGE(A1:A10, 2)"],
    "LCM": ["Least common multiple of the numbers.", "LCM(4, 6)"],
    "LEFT": ["The first characters of a string.", "LEFT(A1, 3)"],
    "LEFTB": ["The first bytes of a string.", "LEFTB(A1, 3)"],
    "LEN": ["Number of characters in text.", "LEN(A1)"],
    "LENB": ["Number of bytes in text.", "LENB(A1)"],
    "LINEST": ["Statistics of the best-fit straight line through the data.", "LINEST(B1:B10, A1:A10)"],
    "LN": ["Natural logarithm of a number.", "LN(10)"],
    "LOG": ["Logarithm of a number to a base (10 when omitted).", "LOG(8, 2)"],
    "LOG10": ["Base-10 logarithm of a number.", "LOG10(1000)"],
    "LOGEST": ["Statistics of the best-fit exponential curve through the data.", "LOGEST(B1:B10, A1:A10)"],
    "LOOKUP": ["Finds a key in a sorted row or column and returns the matching result.", "LOOKUP(A1, D1:D10, E1:E10)"],
    "LOWER": ["Converts text to lower case.", "LOWER(A1)"],
    "LT": ["TRUE when the first value is less. Same as the < operator.", "LT(A1, B1)"],
    "LTE": ["TRUE when the first value is less or equal. Same as <=.", "LTE(A1, B1)"],
    "MATCH": ["Position of a value within a row or column.", "MATCH(\"Apple\", A1:A10, 0)"],
    "MAX": ["Largest number of the values.", "MAX(A1:A10)"],
    "MAXA": ["Largest of the values, counting text as 0 and TRUE as 1.", "MAXA(A1:A10)"],
    "MAXIFS": ["Largest value of a range, over rows that meet every criterion.", "MAXIFS(C1:C10, A1:A10, \"East\")"],
    "MDETERM": ["Determinant of a square matrix.", "MDETERM(A1:C3)"],
    "MEDIAN": ["Middle value of the numbers.", "MEDIAN(A1:A10)"],
    "MID": ["Characters from the middle of a string.", "MID(A1, 2, 3)"],
    "MIDB": ["Bytes from the middle of a string.", "MIDB(A1, 2, 3)"],
    "MIN": ["Smallest number of the values.", "MIN(A1:A10)"],
    "MINA": ["Smallest of the values, counting text as 0 and TRUE as 1.", "MINA(A1:A10)"],
    "MINIFS": ["Smallest value of a range, over rows that meet every criterion.", "MINIFS(C1:C10, A1:A10, \"East\")"],
    "MINUS": ["One number minus another. Same as the - operator.", "MINUS(A1, B1)"],
    "MINUTE": ["Minute component of a time, 0-59.", "MINUTE(A1)"],
    "MINVERSE": ["Inverse of a square matrix.", "MINVERSE(A1:B2)"],
    "MIRR": ["Modified internal rate of return of a series of cash flows.", "MIRR(A1:A6, 0.1, 0.12)"],
    "MMULT": ["Matrix product of two arrays.", "MMULT(A1:B2, D1:E2)"],
    "MOD": ["Remainder after division.", "MOD(10, 3)"],
    "MODE": ["Most common value of the numbers.", "MODE(A1:A10)"],
    "MODE.MULT": ["Every most-common value of the numbers, as a column.", "MODE.MULT(A1:A10)"],
    "MODE.SNGL": ["Most common value of the numbers.", "MODE.SNGL(A1:A10)"],
    "MONTH": ["Month number of a date, 1-12.", "MONTH(A1)"],
    "MROUND": ["Rounds a number to the nearest multiple of factor.", "MROUND(17, 5)"],
    "MULTINOMIAL": ["Factorial of the sum divided by the product of the factorials.", "MULTINOMIAL(2, 3, 4)"],
    "MULTIPLY": ["Product of two numbers. Same as the * operator.", "MULTIPLY(A1, B1)"],
    "MUNIT": ["Identity matrix of the given size.", "MUNIT(3)"],
    "N": ["A value converted to a number (text becomes 0).", "N(A1)"],
    "NA": ["The #N/A error value.", "NA()"],
    "NE": ["TRUE when two values differ. Same as the <> operator.", "NE(A1, B1)"],
    "NETWORKDAYS": ["Working days between two dates, Monday to Friday.", "NETWORKDAYS(A1, B1)"],
    "NETWORKDAYS.INTL": ["Working days between two dates, with custom weekends.", "NETWORKDAYS.INTL(A1, B1, 7)"],
    "NOMINAL": ["Nominal annual interest rate from an effective rate.", "NOMINAL(0.0512, 12)"],
    "NOT": ["Reverses a logical value.", "NOT(A1 > 50)"],
    "NOW": ["Current date and time.", "NOW()"],
    "NPER": ["Number of payment periods for an investment or loan.", "NPER(0.05 / 12, -500, 20000)"],
    "NPV": ["Net present value of a series of cash flows at a discount rate.", "NPV(0.1, B2:B6)"],
    "NUMBERVALUE": ["Converts text to a number, with custom separators.", "NUMBERVALUE(\"1.234,5\", \",\", \".\")"],
    "OCT2BIN": ["Converts an octal number to binary.", "OCT2BIN(\"17\")"],
    "OCT2DEC": ["Converts an octal number to decimal.", "OCT2DEC(\"17\")"],
    "OCT2HEX": ["Converts an octal number to hexadecimal.", "OCT2HEX(\"17\")"],
    "ODD": ["Rounds a number up to the nearest odd integer.", "ODD(2.4)"],
    "OFFSET": ["A range shifted a number of rows and columns from a start cell.", "OFFSET(A1, 2, 1, 3, 1)"],
    "OR": ["TRUE when any argument is TRUE.", "OR(A1 > 90, B1 = \"VIP\")"],
    "PDURATION": ["Periods needed for an investment to reach a value.", "PDURATION(0.05, 1000, 2000)"],
    "PEARSON": ["Pearson correlation coefficient of two data sets.", "PEARSON(B1:B10, A1:A10)"],
    "PERCENTILE": ["Value at a given percentile of a data set.", "PERCENTILE(A1:A10, 0.9)"],
    "PERCENTILE.EXC": ["Value at a percentile, exclusive of 0 and 1.", "PERCENTILE.EXC(A1:A10, 0.9)"],
    "PERCENTILE.INC": ["Value at a percentile, inclusive of 0 and 1.", "PERCENTILE.INC(A1:A10, 0.9)"],
    "PERCENTRANK": ["Rank of a value in a data set, as a percentage.", "PERCENTRANK(A1:A10, 42)"],
    "PERCENTRANK.EXC": ["Percentage rank of a value, exclusive of 0 and 1.", "PERCENTRANK.EXC(A1:A10, 42)"],
    "PERCENTRANK.INC": ["Percentage rank of a value, inclusive of 0 and 1.", "PERCENTRANK.INC(A1:A10, 42)"],
    "PERMUT": ["Number of ordered arrangements of k items from n.", "PERMUT(10, 3)"],
    "PERMUTATIONA": ["Ordered arrangements of k items from n, repetition allowed.", "PERMUTATIONA(3, 2)"],
    "PI": ["The number pi, 3.14159...", "PI()"],
    "PMT": ["Periodic payment for a loan with constant payments and rate.", "PMT(0.05 / 12, 360, 200000)"],
    "POW": ["A number raised to a power.", "POW(2, 10)"],
    "POWER": ["A number raised to a power.", "POWER(2, 10)"],
    "PPMT": ["Principal part of a loan payment for a given period.", "PPMT(0.05 / 12, 1, 360, 200000)"],
    "PROB": ["Probability that values fall between two limits.", "PROB(A1:A4, B1:B4, 2, 3)"],
    "PRODUCT": ["Product of the numbers.", "PRODUCT(A1:A5)"],
    "PROPER": ["Capitalises the first letter of each word.", "PROPER(\"hello world\")"],
    "PV": ["Present value of an investment with periodic payments.", "PV(0.05 / 12, 120, -100)"],
    "QUARTILE": ["Value at a quartile (0-4) of a data set.", "QUARTILE(A1:A10, 1)"],
    "QUARTILE.EXC": ["Quartile of a data set, exclusive of 0 and 1.", "QUARTILE.EXC(A1:A10, 1)"],
    "QUARTILE.INC": ["Quartile of a data set, inclusive of 0 and 1.", "QUARTILE.INC(A1:A10, 1)"],
    "QUOTIENT": ["Integer part of a division.", "QUOTIENT(10, 3)"],
    "RADIANS": ["Converts degrees to radians.", "RADIANS(180)"],
    "RAND": ["Random number from 0 up to 1.", "RAND()"],
    "RANDARRAY": ["An array of random numbers from 0 up to 1.", "RANDARRAY(3, 2)"],
    "RANDBETWEEN": ["Random integer between two values, inclusive.", "RANDBETWEEN(1, 6)"],
    "RANK": ["Rank of a value within a data set.", "RANK(A1, A1:A10)"],
    "RANK.AVG": ["Rank of a value, averaging the ranks of ties.", "RANK.AVG(A1, A1:A10)"],
    "RANK.EQ": ["Rank of a value, ties sharing the top rank.", "RANK.EQ(A1, A1:A10)"],
    "RATE": ["Interest rate per period of an annuity.", "RATE(60, -400, 20000)"],
    "REGEXEXTRACT": ["The first part of text that matches a regular expression.", "REGEXEXTRACT(A1, \"[0-9]+\")"],
    "REGEXMATCH": ["TRUE when text matches a regular expression.", "REGEXMATCH(A1, \"^[A-Z]\")"],
    "REGEXREPLACE": ["Replaces the parts of text that match a regular expression.", "REGEXREPLACE(A1, \"[0-9]\", \"#\")"],
    "REPLACE": ["Replaces part of text at a given position.", "REPLACE(A1, 1, 3, \"New\")"],
    "REPLACEB": ["Replaces part of text at a given byte position.", "REPLACEB(A1, 1, 3, \"New\")"],
    "REPT": ["Text repeated a number of times.", "REPT(\"-\", 10)"],
    "RIGHT": ["The last characters of a string.", "RIGHT(A1, 4)"],
    "RIGHTB": ["The last bytes of a string.", "RIGHTB(A1, 4)"],
    "ROMAN": ["Converts a number to a Roman numeral.", "ROMAN(2026)"],
    "ROUND": ["Rounds a number to a number of decimal places.", "ROUND(3.14159, 2)"],
    "ROUNDDOWN": ["Rounds a number towards zero.", "ROUNDDOWN(3.789, 1)"],
    "ROUNDUP": ["Rounds a number away from zero.", "ROUNDUP(3.211, 1)"],
    "ROW": ["Row number of a cell (of this cell when omitted).", "ROW(C5)"],
    "ROWS": ["Number of rows in a range.", "ROWS(A1:D10)"],
    "RRI": ["Equivalent interest rate for an investment's growth.", "RRI(10, 1000, 2000)"],
    "RSQ": ["Square of the Pearson correlation coefficient.", "RSQ(B1:B10, A1:A10)"],
    "SEARCH": ["Position of text inside other text, ignoring case.", "SEARCH(\"apple\", A1)"],
    "SEARCHB": ["Byte position of text inside other text, ignoring case.", "SEARCHB(\"b\", \"ABC\")"],
    "SEC": ["Secant of an angle given in radians.", "SEC(PI())"],
    "SECH": ["Hyperbolic secant of a number.", "SECH(1)"],
    "SECOND": ["Second component of a time, 0-59.", "SECOND(A1)"],
    "SEQUENCE": ["An array of sequential numbers.", "SEQUENCE(5, 1, 1, 1)"],
    "SERIESSUM": ["Sum of a power series.", "SERIESSUM(2, 0, 1, {1, 2, 3})"],
    "SHEET": ["Sheet number of a reference or sheet name.", "SHEET(\"Sheet2\")"],
    "SHEETS": ["Number of sheets in the workbook (or in a reference).", "SHEETS()"],
    "SIGN": ["-1, 0 or 1 by the sign of a number.", "SIGN(A1)"],
    "SIN": ["Sine of an angle given in radians.", "SIN(PI() / 2)"],
    "SINGLE": ["A single value from a range, by implicit intersection.", "SINGLE(A1:A10)"],
    "SINH": ["Hyperbolic sine of a number.", "SINH(1)"],
    "SKEW": ["Sample skewness of a data set.", "SKEW(A1:A10)"],
    "SKEW.P": ["Population skewness of a data set.", "SKEW.P(A1:A10)"],
    "SLN": ["Straight-line depreciation for one period.", "SLN(10000, 1000, 5)"],
    "SLOPE": ["Slope of the linear regression line.", "SLOPE(B1:B10, A1:A10)"],
    "SMALL": ["The n-th smallest value of a data set.", "SMALL(A1:A10, 2)"],
    "SORT": ["The rows of a range, sorted by one or more columns.", "SORT(A1:C10, 2, FALSE)"],
    "SORTN": ["The first n rows of a range after sorting.", "SORTN(A1:C10, 3, 0, 2, FALSE)"],
    "SPLIT": ["Splits text at a delimiter into separate cells.", "SPLIT(A1, \",\")"],
    "SQRT": ["Square root of a number.", "SQRT(16)"],
    "SQRTPI": ["Square root of a number multiplied by pi.", "SQRTPI(2)"],
    "STANDARDIZE": ["Normalised (z-score) value for a mean and standard deviation.", "STANDARDIZE(A1, 50, 10)"],
    "STDEV": ["Sample standard deviation.", "STDEV(A1:A10)"],
    "STDEV.P": ["Population standard deviation.", "STDEV.P(A1:A10)"],
    "STDEV.S": ["Sample standard deviation.", "STDEV.S(A1:A10)"],
    "STDEVA": ["Sample standard deviation, counting text as 0 and TRUE as 1.", "STDEVA(A1:A10)"],
    "STDEVP": ["Population standard deviation.", "STDEVP(A1:A10)"],
    "STDEVPA": ["Population standard deviation, counting text as 0 and TRUE as 1.", "STDEVPA(A1:A10)"],
    "STEYX": ["Standard error of the predicted y in a linear regression.", "STEYX(B1:B10, A1:A10)"],
    "SUBSTITUTE": ["Replaces occurrences of some text with new text.", "SUBSTITUTE(A1, \"old\", \"new\")"],
    "SUBTOTAL": ["A subtotal (SUM, AVERAGE, ...) chosen by function code, skipping other subtotals.", "SUBTOTAL(9, A1:A10)"],
    "SUM": ["Sum of the numbers.", "SUM(A1:A10)"],
    "SUMIF": ["Sum of the cells that meet one criterion.", "SUMIF(A1:A10, \"East\", C1:C10)"],
    "SUMIFS": ["Sum of a range, over rows that meet every criterion.", "SUMIFS(C1:C10, A1:A10, \"East\", B1:B10, \">100\")"],
    "SUMPRODUCT": ["Sum of the products of matching entries of arrays.", "SUMPRODUCT(A1:A5, B1:B5)"],
    "SUMSQ": ["Sum of the squares of the numbers.", "SUMSQ(A1:A5)"],
    "SUMX2MY2": ["Sum of the differences of squares of two arrays.", "SUMX2MY2(A1:A5, B1:B5)"],
    "SUMX2PY2": ["Sum of the sums of squares of two arrays.", "SUMX2PY2(A1:A5, B1:B5)"],
    "SUMXMY2": ["Sum of the squared differences of two arrays.", "SUMXMY2(A1:A5, B1:B5)"],
    "SWITCH": ["The value matching the first case equal to the expression.", "SWITCH(A1, 1, \"One\", 2, \"Two\", \"Other\")"],
    "SYD": ["Sum-of-years'-digits depreciation for a period.", "SYD(10000, 1000, 5, 1)"],
    "T": ["The value if it is text, otherwise empty text.", "T(A1)"],
    "TAKE": ["Rows (and columns) taken from the start or end of an array.", "TAKE(A1:D10, 3)"],
    "TAN": ["Tangent of an angle given in radians.", "TAN(PI() / 4)"],
    "TANH": ["Hyperbolic tangent of a number.", "TANH(1)"],
    "TEXT": ["Formats a number as text with a number format.", "TEXT(A1, \"0.00%\")"],
    "TEXTAFTER": ["The text after a delimiter.", "TEXTAFTER(A1, \"@\")"],
    "TEXTBEFORE": ["The text before a delimiter.", "TEXTBEFORE(A1, \"@\")"],
    "TEXTJOIN": ["Joins text with a delimiter, optionally skipping empty cells.", "TEXTJOIN(\", \", TRUE, A1:A5)"],
    "TEXTSPLIT": ["Splits text into columns (and rows) at delimiters.", "TEXTSPLIT(A1, \",\")"],
    "TIME": ["Time built from an hour, minute and second.", "TIME(14, 30, 0)"],
    "TIMEVALUE": ["Converts text that looks like a time into a time.", "TIMEVALUE(\"2:30 PM\")"],
    "TOCOL": ["All values of an array in a single column.", "TOCOL(A1:C3)"],
    "TODAY": ["Today's date.", "TODAY()"],
    "TOROW": ["All values of an array in a single row.", "TOROW(A1:C3)"],
    "TO_DATE": ["A number shown as a date.", "TO_DATE(46287)"],
    "TO_DOLLARS": ["A number shown as currency.", "TO_DOLLARS(A1)"],
    "TO_PERCENT": ["A number shown as a percentage.", "TO_PERCENT(0.25)"],
    "TO_PURE_NUMBER": ["A value stripped of its date, currency or percent formatting.", "TO_PURE_NUMBER(A1)"],
    "TO_TEXT": ["A value converted to text.", "TO_TEXT(A1)"],
    "TRANSPOSE": ["Swaps the rows and columns of an array.", "TRANSPOSE(A1:C2)"],
    "TREND": ["Values predicted along a linear trend.", "TREND(B1:B10, A1:A10, A11:A12)"],
    "TRIM": ["Removes leading, trailing and repeated spaces.", "TRIM(A1)"],
    "TRIMMEAN": ["Mean of a data set, excluding a proportion of the extremes.", "TRIMMEAN(A1:A20, 0.1)"],
    "TRUE": ["The logical value TRUE.", "TRUE()"],
    "TRUNC": ["Truncates a number to a number of decimal places.", "TRUNC(3.789, 1)"],
    "TYPE": ["Number for the type of a value (1 number, 2 text, 4 logical, 16 error, 64 array).", "TYPE(A1)"],
    "UMINUS": ["A number with its sign reversed.", "UMINUS(A1)"],
    "UNARY_PERCENT": ["A value divided by 100.", "UNARY_PERCENT(25)"],
    "UNICHAR": ["Unicode character for a code point.", "UNICHAR(9731)"],
    "UNICODE": ["Unicode code point of the first character of text.", "UNICODE(\"A\")"],
    "UNIQUE": ["The distinct rows of a range.", "UNIQUE(A1:A20)"],
    "UPLUS": ["The number unchanged.", "UPLUS(A1)"],
    "UPPER": ["Converts text to upper case.", "UPPER(A1)"],
    "VALUE": ["Converts text that looks like a number into a number.", "VALUE(\"42\")"],
    "VAR": ["Sample variance.", "VAR(A1:A10)"],
    "VAR.P": ["Population variance.", "VAR.P(A1:A10)"],
    "VAR.S": ["Sample variance.", "VAR.S(A1:A10)"],
    "VARA": ["Sample variance, counting text as 0 and TRUE as 1.", "VARA(A1:A10)"],
    "VARP": ["Population variance.", "VARP(A1:A10)"],
    "VARPA": ["Population variance, counting text as 0 and TRUE as 1.", "VARPA(A1:A10)"],
    "VDB": ["Depreciation over a span of periods, by a declining-balance method.", "VDB(10000, 1000, 5, 0, 1)"],
    "VLOOKUP": ["Finds a key in the first column of a range and returns a value from another column.", "VLOOKUP(A1, D1:F10, 3, FALSE)"],
    "VSTACK": ["Arrays stacked on top of each other into one array.", "VSTACK(A1:C1, A5:C8)"],
    "WEEKDAY": ["Day of the week of a date, as a number.", "WEEKDAY(A1, 2)"],
    "WEEKNUM": ["Week number of the year of a date.", "WEEKNUM(A1)"],
    "WORKDAY": ["Date a number of working days from a start date.", "WORKDAY(A1, 10)"],
    "WORKDAY.INTL": ["Date a number of working days away, with custom weekends.", "WORKDAY.INTL(A1, 10, 7)"],
    "WRAPCOLS": ["A row or column wrapped into columns of a given length.", "WRAPCOLS(A1:A12, 4)"],
    "WRAPROWS": ["A row or column wrapped into rows of a given length.", "WRAPROWS(A1:A12, 4)"],
    "XIRR": ["Internal rate of return for cash flows on specific dates.", "XIRR(B1:B5, A1:A5)"],
    "XLOOKUP": ["Finds a key in one range and returns the matching item from another.", "XLOOKUP(A1, D1:D10, E1:E10, \"Not found\")"],
    "XMATCH": ["Position of a value in a range, with match and search modes.", "XMATCH(\"Apple\", A1:A10)"],
    "XNPV": ["Net present value of cash flows on specific dates.", "XNPV(0.09, B1:B5, A1:A5)"],
    "XOR": ["TRUE when an odd number of arguments are TRUE.", "XOR(A1 > 0, B1 > 0)"],
    "YEAR": ["Year of a date.", "YEAR(A1)"],
    "YEARFRAC": ["Fraction of a year between two dates.", "YEARFRAC(A1, B1)"]
};
if (typeof module !== "undefined" && module.exports) module.exports = SheetFormulaHelp;
