package metadata

import (
	"bytes"
	"encoding/base64"
	"image"
	"image/color"
	"image/png"
	"strings"
	"testing"
)

// encodePNG builds a tiny solid colour PNG and returns it base64 encoded the
// way a slicer would embed it.
func encodePNG(t *testing.T, width, height int, c color.Color) string {
	t.Helper()
	img := image.NewRGBA(image.Rect(0, 0, width, height))
	for y := 0; y < height; y++ {
		for x := 0; x < width; x++ {
			img.Set(x, y, c)
		}
	}
	var buf bytes.Buffer
	if err := png.Encode(&buf, img); err != nil {
		t.Fatalf("could not encode test png: %v", err)
	}
	return base64.StdEncoding.EncodeToString(buf.Bytes())
}

// gcodeWithThumbnail wraps base64 payload in slicer style comment markers.
func gcodeWithThumbnail(header string, payload string, footer string) string {
	var sb strings.Builder
	sb.WriteString(header)
	for len(payload) > 0 {
		chunk := payload
		if len(chunk) > 78 {
			chunk = chunk[:78]
		}
		payload = payload[len(chunk):]
		sb.WriteString("; " + chunk + "\n")
	}
	sb.WriteString(footer)
	return sb.String()
}

func TestExtractGcodeThumbnails(t *testing.T) {
	small := encodePNG(t, 4, 2, color.RGBA{255, 0, 0, 255})
	large := encodePNG(t, 8, 8, color.RGBA{0, 255, 0, 255})

	tests := []struct {
		name      string
		source    string
		wantCount int
		wantFirst string // "WxH" of the first extracted thumbnail
	}{
		{
			name:      "no thumbnail",
			source:    "G28\nG1 X10 Y10\n; just a comment\n",
			wantCount: 0,
		},
		{
			name: "single prusa style block",
			source: gcodeWithThumbnail(
				"; generated by TestSlicer\n; thumbnail begin 4x2 100\n", small, "; thumbnail end\nG28\n"),
			wantCount: 1,
			wantFirst: "4x2",
		},
		{
			name: "format suffix and no space after marker",
			source: gcodeWithThumbnail(
				";thumbnail_JPG begin 4x2 100\n", small, ";thumbnail_JPG end\n"),
			wantCount: 1,
			wantFirst: "4x2",
		},
		{
			name: "two blocks keeps document order",
			source: gcodeWithThumbnail("; thumbnail begin 4x2 100\n", small, "; thumbnail end\n") +
				gcodeWithThumbnail("; thumbnail begin 8x8 200 top\n", large, "; thumbnail end\n"),
			wantCount: 2,
			wantFirst: "4x2",
		},
		{
			name:      "unterminated block is discarded",
			source:    gcodeWithThumbnail("; thumbnail begin 4x2 100\n", small, "G28\n"),
			wantCount: 0,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := extractGcodeThumbnails(strings.NewReader(tt.source))
			if err != nil {
				t.Fatalf("extractGcodeThumbnails returned error: %v", err)
			}
			if len(got) != tt.wantCount {
				t.Fatalf("got %d thumbnails, want %d", len(got), tt.wantCount)
			}
			if tt.wantCount == 0 {
				return
			}
			first := itoa(got[0].width) + "x" + itoa(got[0].height)
			if first != tt.wantFirst {
				t.Errorf("first thumbnail is %s, want %s", first, tt.wantFirst)
			}
			if len(got[0].data) == 0 {
				t.Error("first thumbnail carries no decoded payload")
			}
		})
	}
}

func TestPickGcodeThumbnails(t *testing.T) {
	tests := []struct {
		name  string
		input []gcodeThumbnail
		want  string // "WxH" expected to be ranked first
	}{
		{
			name:  "largest untagged wins",
			input: []gcodeThumbnail{{width: 16, height: 16}, {width: 64, height: 64}, {width: 32, height: 32}},
			want:  "64x64",
		},
		{
			name:  "untagged beats a larger tagged preview",
			input: []gcodeThumbnail{{width: 512, height: 512, tag: "top"}, {width: 230, height: 110}},
			want:  "230x110",
		},
		{
			name:  "falls back to tagged when nothing is untagged",
			input: []gcodeThumbnail{{width: 100, height: 100, tag: "top"}, {width: 400, height: 400, tag: "front"}},
			want:  "400x400",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := pickGcodeThumbnails(tt.input)
			first := itoa(got[0].width) + "x" + itoa(got[0].height)
			if first != tt.want {
				t.Errorf("ranked %s first, want %s", first, tt.want)
			}
			if len(got) != len(tt.input) {
				t.Errorf("got %d candidates back, want %d", len(got), len(tt.input))
			}
		})
	}
}

func TestDecodeGcodeThumbnail(t *testing.T) {
	small := encodePNG(t, 4, 2, color.RGBA{255, 0, 0, 255})
	large := encodePNG(t, 8, 8, color.RGBA{0, 255, 0, 255})

	t.Run("decodes the preferred candidate", func(t *testing.T) {
		source := gcodeWithThumbnail("; thumbnail begin 8x8 200 top\n", large, "; thumbnail end\n") +
			gcodeWithThumbnail("; thumbnail begin 4x2 100\n", small, "; thumbnail end\n")
		img, err := decodeGcodeThumbnail(strings.NewReader(source))
		if err != nil {
			t.Fatalf("decodeGcodeThumbnail returned error: %v", err)
		}
		// the untagged 4x2 preview should win over the tagged 8x8 one
		if got := img.Bounds().Dx(); got != 4 {
			t.Errorf("decoded a %dpx wide image, want the 4px untagged preview", got)
		}
	})

	t.Run("skips an undecodable candidate", func(t *testing.T) {
		junk := base64.StdEncoding.EncodeToString([]byte("qoif not a real image payload"))
		source := gcodeWithThumbnail("; thumbnail begin 99x99 100\n", junk, "; thumbnail end\n") +
			gcodeWithThumbnail("; thumbnail begin 8x8 200\n", large, "; thumbnail end\n")
		img, err := decodeGcodeThumbnail(strings.NewReader(source))
		if err != nil {
			t.Fatalf("decodeGcodeThumbnail returned error: %v", err)
		}
		if got := img.Bounds().Dx(); got != 8 {
			t.Errorf("decoded a %dpx wide image, want the 8px fallback", got)
		}
	})

	t.Run("reports a file without any thumbnail", func(t *testing.T) {
		_, err := decodeGcodeThumbnail(strings.NewReader("G28\nG1 X1 Y1 E1\n"))
		if err == nil {
			t.Error("expected an error for a gcode file with no embedded thumbnail")
		}
	})
}

func TestTrimTransparent(t *testing.T) {
	// a 200x100 canvas with an opaque 20x40 block at (90,30)
	withBlock := func() image.Image {
		img := image.NewRGBA(image.Rect(0, 0, 200, 100))
		for y := 30; y < 70; y++ {
			for x := 90; x < 110; x++ {
				img.Set(x, y, color.RGBA{200, 200, 40, 255})
			}
		}
		return img
	}

	tests := []struct {
		name                  string
		src                   image.Image
		wantSmallerThanSource bool
	}{
		{name: "crops the transparent margin", src: withBlock(), wantSmallerThanSource: true},
		{
			name: "leaves a fully opaque image alone",
			src: func() image.Image {
				img := image.NewRGBA(image.Rect(0, 0, 40, 40))
				for y := 0; y < 40; y++ {
					for x := 0; x < 40; x++ {
						img.Set(x, y, color.RGBA{10, 20, 30, 255})
					}
				}
				return img
			}(),
			wantSmallerThanSource: false,
		},
		{
			name:                  "leaves a fully transparent image alone",
			src:                   image.NewRGBA(image.Rect(0, 0, 40, 40)),
			wantSmallerThanSource: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			srcArea := tt.src.Bounds().Dx() * tt.src.Bounds().Dy()
			got := trimTransparent(tt.src)
			gotArea := got.Bounds().Dx() * got.Bounds().Dy()

			if tt.wantSmallerThanSource && gotArea >= srcArea {
				t.Errorf("trimmed area %d is not smaller than the source area %d", gotArea, srcArea)
			}
			if !tt.wantSmallerThanSource && gotArea != srcArea {
				t.Errorf("trimmed area %d, want the source area %d untouched", gotArea, srcArea)
			}
			if gotArea == 0 {
				t.Error("trimming produced an empty image")
			}
		})
	}
}

func TestFitOnCanvas(t *testing.T) {
	tests := []struct {
		name          string
		width, height int
	}{
		{name: "wide preview", width: 230, height: 110},
		{name: "square preview", width: 512, height: 512},
		{name: "tall preview", width: 100, height: 400},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			src := image.NewRGBA(image.Rect(0, 0, tt.width, tt.height))
			got := fitOnCanvas(src, 480, color.White)
			bounds := got.Bounds()
			if bounds.Dx() != 480 || bounds.Dy() != 480 {
				t.Errorf("canvas is %dx%d, want 480x480", bounds.Dx(), bounds.Dy())
			}
			// corners must be filled with the background, never left transparent
			_, _, _, alpha := got.At(0, 0).RGBA()
			if alpha != 0xffff {
				t.Errorf("corner alpha is %d, want an opaque background", alpha)
			}
		})
	}
}

// itoa keeps the table assertions readable without pulling in strconv here.
func itoa(v int) string {
	if v == 0 {
		return "0"
	}
	digits := ""
	for v > 0 {
		digits = string(rune('0'+v%10)) + digits
		v /= 10
	}
	return digits
}
