package shortcut

import (
	"testing"
)

func TestGenerateShortcutBytes(t *testing.T) {
	// Test generating shortcut bytes
	bytes := GenerateShortcutBytes("/test/path", "file", "test", "icon.png")
	if len(bytes) == 0 {
		t.Error("Generated bytes should not be empty")
	}
}
